/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InstanceFieldDemo */

#ifndef _Included_InstanceFieldDemo
#define _Included_InstanceFieldDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InstanceFieldDemo
 * Method:    accessField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InstanceFieldDemo_accessField
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
